platform :ios, '8.0'
use_frameworks!

react_native = {:git => 'https://github.com/getsiphon/react-native.git', :commit => '0388697'}

pod 'React', react_native
pod 'React/ART', react_native
pod 'React/RCTActionSheet', react_native
pod 'React/RCTGeolocation', react_native
pod 'React/RCTImage', react_native
pod 'React/RCTNetwork', react_native
pod 'React/RCTPushNotification', react_native
pod 'React/RCTSettings', react_native
pod 'React/RCTText', react_native
pod 'React/RCTVibration', react_native
pod 'React/RCTWebSocket', react_native
pod 'React/RCTLinkingIOS', react_native

pod 'FBSDKCoreKit', '4.12.0'
pod 'FBSDKLoginKit', '4.12.0'
pod 'FBSDKShareKit', '4.12.0'
pod 'Mixpanel', '2.9.0'
pod 'SSZipArchive', '0.3.3'
pod 'SocketRocket', '0.4.2'
pod 'Siphon', :git => 'https://getsiphon:CHANGEME@bitbucket.org/getsiphon/siphon-sdk-ios.git', :commit => '978e899'
